### PR TITLE
Add an api key as a part of push notifications signature

### PR DESCRIPTION
**Pull request by nyarian**
tari-project/wallet-android#399
Add an api key as a part of push notifications signature

### CODE REVIEW

**Comment by nyarian** [comment]
> Let's keep the sample secret props file and the copy procedure as part of the build config.

@kukabi secret-example.properties will contain an invalid sentry url for sure, thus causing app failure at runtime instead of build time, so copying can be considered rather harmful

would it work if secret-example.properties will be present in the project just to highlight that "there is a secret props file somewhere"?

**Comment by kukabi** [comment]
> > Let's keep the sample secret props file and the copy procedure as part of the build config.
> 
> @kukabi secret-example.properties will contain an invalid sentry url for sure, thus causing app failure at runtime instead of build time, so copying can be considered rather harmful
> 
> would it work if secret-example.properties will be present in the project just to highlight that "there is a secret props file somewhere"?

@nyarian `https://0@your.sentry.dsn/0 ` this sample DSN in the example file is correctly formed and it doesn't cause a runtime error, it was tested. A malformed DSN or empty value made Sentry crash the app the last time I tested it.

When the project is first configured `secret.properties` gets generated as a copy of the example file, and it contains this sample DSN (and any other value that should exist in the properties file for the app to function fully), and yes it does explicitly show to the developer/tester that there's a properties file that is in use. It doesn't have to be named `secret.properties`, it could be called `config.properties` or something, and the example file should contain sample values that won't break the app when run as they are.

**Comment by nyarian** [comment]
@kukabi 
If anyone is determined to assemble a regular build as is (it's hard to expect that users will inspect and get the purpose of every project's file before running anything, especially if he does not posses any former Android development experience), expecting that Sentry crash reporting should work as expected, then, in the best case, the application won't behave as this user expects and crash reports won't be sent.

Are you OK with this? If yes, than I'll just make the requested changes.

**Comment by kukabi** [comment]
Sure yes, they can configure Sentry through the properties file once they're able to build & run the whole app, and the first run should put everything required in place as it currently does on the dev branch. Let's keep the sample properties file exactly as it was with correctly formed dummy Sentry DSN and any additional property that we might be using. @nyarian

**Pull request merged**
