### PR TITLE
Fix add recipient fragment crash on lower android versions

### LINKED ISSUE #172: IBM ICU library takes up too much space.
`icu4j`, which we use to process emojis, takes up around 22MB in the distributable bundle. Let's find out if it takes up this much space on the actual device, and if so, let's try to find a way of minimizing it, or to use a smaller library or get rid of this library altogether.
Screen Shot 2020-03-19 at 14 42 04

### PR DESCRIPTION
**Pull request by jigneshsanghani**
Closes #172

Uses android platform ICU lib and gets rid of integrated library, this should reduce APK size by ~9mb.

### CODE REVIEW

**Comment by kukabi** [comment]
IBM ICU library was introduced because the Android ICU library did not process the emojis correctly. Actually I found that the IBM library was the only library around that accurately processed any kind of emoji. Please make a thorough test to make sure the native ICU doesn't break our emoji functions.

**Comment by kukabi** [comment]
...and some Android ICU library features are available from v28 upwards. Warning below makes the app crash in `AddRecipientFragment`.

Screen Shot 2020-03-24 at 14 32 40

**Comment by kukabi** [comment]
update per @jigneshsanghani's find: the crash is being caused by something else but the emoji functions don't work correctly under v28.

**Comment by jigneshsanghani** [comment]
Replace library with a compact version and fixed the crash.

**Comment by jigneshsanghani** [comment]
Reverted library change, couldn't find better library than ibm ICU. However, we should merge crash fix.

**Pull request merged**
